export const letters = [
  {character: 'a', score: 1},
  {character: 'b', score: 3},
  {character: 'c', score: 3},
  {character: 'd', score: 2},
  {character: 'e', score: 1},
  {character: 'f', score: 4},
  {character: 'g', score: 2},
  {character: 'h', score: 4},
  {character: 'i', score: 1},
  {character: 'j', score: 8},
  {character: 'k', score: 5},
  {character: 'l', score: 1},
  {character: 'm', score: 3},
  {character: 'n', score: 1},
  {character: 'o', score: 1},
  {character: 'p', score: 3},
  {character: 'q', score: 10},
  {character: 'r', score: 1},
  {character: 's', score: 1},
  {character: 't', score: 1},
  {character: 'u', score: 1},
  {character: 'v', score: 4},
  {character: 'w', score: 4},
  {character: 'x', score: 8},
  {character: 'y', score: 4},
  {character: 'z', score: 10}
]

